const template = {
    id: 'skin_number',
    name: 'skin_name',
    date_start: 'date_start',
    date_end: 'date_end',
    url: 'url',
    video_url: 'url',
    images: [
        {
            name: 'image_name',
            url: 'url',
            image_url: '01/thing.jpg',
            isGameplay: false,
        }
    ]
}

const skins = [
    {
        id: '01',
        name: 'custom',
        date_start: '2020-01-05',
        date_end: '2020-05-09',
        url: 'https://mega.nz/folder/XUFzRa7S#ZeTijOa3mmVaBAEBlz9WPg',
        video_url: 'https://www.youtube.com/embed/RmjwBr_NECQ',
        images: [
            {
                name: 'Gameplay',
                url: 'https://mega.nz/file/uMsFBQ7D#VvU2YpjK1ASbLqyffl2CgsDKNrT3dyX9U2e9C4OBz5Q',
                image_url: '01/game.jpg',
                isGameplay: true,
            },
            {
                name: 'Song select',
                url: 'url',
                image_url: '01/screenshot599.jpg',
                isGameplay: false,
            },
            {
                name: 'Mod select',
                url: 'url',
                image_url: '01/screenshot600.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking panel',
                url: 'url',
                image_url: '01/screenshot601.jpg',
                isGameplay: false,
            },
        ]
    },
    {
        id: '02',
        name: 'customv2',
        date_start: '2020-05-09',
        date_end: '2020-07-01',
        url: 'https://mega.nz/folder/WUFxwY4T#Yw15SF8jYnQ3bDubQuDjUA',
        video_url: 'https://www.youtube.com/embed/KZa6RFBkd5k',
        images: [
            {
                name: 'Gameplay',
                url: 'https://mega.nz/file/jF1jxQiL#mmjKa14JM7THqo3HyBcYodadBhlCfEmWToj0vCg0nwk',
                image_url: '--02_custom2.jpg',
                isGameplay: true,
            },
            {
                name: 'Song select',
                url: 'url',
                image_url: '02/screenshot602.jpg',
                isGameplay: false,
            },
            {
                name: 'Mod select',
                url: 'url',
                image_url: '02/screenshot603.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking panel',
                url: 'url',
                image_url: '02/screenshot604.jpg',
                isGameplay: false,
            },
        ]
    },
    {
        id: '03',
        name: '『SaberStrike [Type X]』',
        date_start: '2020-07-01',
        date_end: '2020-07-25',
        url: 'https://mega.nz/folder/qIN3TYqb#mnLM0hJsSk5wgodu9QelJQ',
        video_url: 'https://www.youtube.com/embed/cuSALg1xZ-k',
        images: [
            {
                name: 'Gameplay',
                url: 'https://mega.nz/file/yVt3HYzZ#2RG6H4tXymO_40m96oHz6iaPgsqkdf3Ov8S2_MbYkCk',
                image_url: '03_typex.jpg',
                isGameplay: true,
            },
            {
                name: 'Song select',
                url: 'url',
                image_url: '03/screenshot605.jpg',
                isGameplay: false,
            },
            {
                name: 'Mod select',
                url: 'url',
                image_url: '03/screenshot606.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking panel',
                url: 'url',
                image_url: '03/screenshot607.jpg',
                isGameplay: false,
            },
        ]
    },
    {
        id: '04',
        name: 'SaberStrike 『Y』',
        date_start: '2020-07-25',
        date_end: '2020-09-24',
        url: 'https://mega.nz/folder/qRFhSSSR#jZ4ewmcB3yZbnwsVlLWBwQ',
        video_url: 'https://www.youtube.com/embed/XPxZqoRjpEs',
        images: [
            {
                name: 'Gameplay',
                url: 'https://mega.nz/file/6EkDQCDK#efa2XqGfH_wXNKsWVocpwiH2bxCMhZvf0Q6C_6ZT7gI',
                image_url: '04_typey',
                isGameplay: true,
            },
            {
                name: 'Song select',
                url: 'url',
                image_url: '04/screenshot608.jpg',
                isGameplay: false,
            },
            {
                name: 'Mod select',
                url: 'url',
                image_url: '04/screenshot609.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking panel',
                url: 'url',
                image_url: '04/screenshot610.jpg',
                isGameplay: false,
            },

        ]
    },
    {
        id: '05',
        name: 'SaberStrike 『Z』',
        date_start: '2020-09-24',
        date_end: '2020-12-05',
        url: 'https://mega.nz/folder/mFkglQqR#hSfKuZ_Mb28O8az7Ry2eew',
        video_url: 'https://www.youtube.com/embed/37e_UhoC1_0',
        images: [
            {
                name: 'Gameplay',
                url: 'https://mega.nz/file/OVtjGYZJ#wjyqmyXSOG0UsGxec9gqZXveVLO77YX4bx3Lb2aI9Mk',
                image_url: '05_typez.jpg',
                isGameplay: true,
            },
            {
                name: 'Song select',
                url: 'url',
                image_url: '05/screenshot611.jpg',
                isGameplay: false,
            },
            {
                name: 'Mod select',
                url: 'url',
                image_url: '05/screenshot612.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking panel',
                url: 'url',
                image_url: '05/screenshot613.jpg',
                isGameplay: false,
            },

        ]
    },
    {
        id: '06',
        name: 'SaberStrike 『0』',
        date_start: '2020-12-05',
        date_end: '2021-02-24',
        url: 'https://mega.nz/folder/2B92nITD#heJQCPP17EocSkDNbwz0TQ',
        video_url: 'https://www.youtube.com/embed/DsN5K7FdxYA',
        images: [
            {
                name: 'Song select',
                url: 'url',
                image_url: '06/songselect.jpg',
                isGameplay: false,
            },
            {
                name: 'Mod select',
                url: 'url',
                image_url: '06/rank.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking panel',
                url: 'url',
                image_url: '06/mods.jpg',
                isGameplay: false,
            },
            {
                name: 'Gameplay',
                url: 'https://mega.nz/file/LJ8VEIZS#SUSFCOdcD-9Q6k-JXMdSRbcnwswqftDQVj9as9mCQiA',
                image_url: '06/game.jpg',
                isGameplay: true,
            },
            {
                name: 'Gameplay (2)',
                url: 'https://mega.nz/file/LJ8VEIZS#SUSFCOdcD-9Q6k-JXMdSRbcnwswqftDQVj9as9mCQiA',
                image_url: '06/game2.jpg',
                isGameplay: true,
            },
        ]
    },
    {
        id: '07',
        name: 'SaberStrike 『1』',
        date_start: '2021-02-24',
        date_end: '2021-06-12',
        url: 'https://mega.nz/folder/OVsklaLJ#DeHiVwoj96wBBw5uQKasEg',
        video_url: 'https://www.youtube.com/embed/JlR4kpCkwNc',
        images: [
            {
                name: 'Gameplay',
                url: 'https://mega.nz/file/6ccTTSJA#b1XYKubUPjzfWHjobfd2vskDQQCsb3XRrD7bdTVJ_Kc',
                image_url: '07/game.jpg',
                isGameplay: true,
            },
            {
                name: 'Song select',
                url: 'url',
                image_url: '07/ranking.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking panel',
                url: 'url',
                image_url: '07/songsel.jpg',
                isGameplay: false,
            },

        ]
    },
    {
        id: '08',
        name: 'sbr (SaberStrike 『2』)',
        date_start: '2021-06-12',
        date_end: '2021-09-05',
        url: 'https://mega.nz/folder/uFtikR7B#rLFVhcbuoOBrEGBulMikDg',
        video_url: 'https://www.youtube.com/embed/SMluwNKWrOM',
        images: [
            {
                name: 'Song select',
                url: 'url',
                image_url: '08/songselec.jpg',
                isGameplay: false,
            },
            {
                name: 'Mode select',
                url: 'url',
                image_url: '08/mode.jpg',
                isGameplay: false,
            },
            {
                name: 'Mod select',
                url: 'url',
                image_url: '08/mods.jpg',
                isGameplay: false,
            },
            {
                name: 'Options',
                url: 'url',
                image_url: '08/opt.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking panel',
                url: 'url',
                image_url: '08/ranking.jpg',
                isGameplay: false,
            },
            {
                name: '-h',
                url: 'https://mega.nz/file/aUkBUAzb#uqyZVEPpUeUJn3aqDMZlqqxlt6LqvVSerJKQ0uSOCqM',
                image_url: '08/game-h.jpg',
                isGameplay: true,
            },
            {
                name: '-s',
                url: 'https://mega.nz/file/DAt3nIja#kQN1iPsQyAe0O-XztVyExo5CaJNaxSzxE97SSPvbufo',
                image_url: '08/game-s.jpg',
                isGameplay: true,
            },
            {
                name: 'DT',
                url: 'https://mega.nz/file/fQNChJra#6HFsFjX37tP3RScfodhEFtz-Xp_GTkV3hTUK5QjpJ38',
                image_url: '08/game-dt.jpg',
                isGameplay: true,
            },
            {
                name: 'EZ',
                url: 'https://mega.nz/file/SJ8ziA5A#lGfgCoSLoc8otw8A_DkVQSuH-z9QlH7CFmbW-HXcigM',
                image_url: '08/game-ez.jpg',
                isGameplay: true,
            },
        ]
    },
    {
        id: '09',
        name: 'prjct. sbr',
        date_start: '2021-09-05',
        date_end: '2021-10-18',
        url: 'https://mega.nz/folder/CB1Q2KZR#mhx0yc3f5okj8LxHziGgTg',
        video_url: 'https://www.youtube.com/embed/WdYl4IFLjdo',
        images: [
            {
                name: 'Song select',
                url: 'url',
                image_url: '09/songselec.jpg',
                isGameplay: false,
            },
            {
                name: 'Mode select',
                url: 'url',
                image_url: '09/mode.jpg',
                isGameplay: false,
            },
            {
                name: 'Mod select',
                url: 'url',
                image_url: '09/mods.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking panel',
                url: 'url',
                image_url: '09/ranking.jpg',
                isGameplay: false,
            },
            {
                name: 'Main',
                url: 'https://mega.nz/file/iZ1Rka4B#LhSLuDlYoX3bejOmpjltOZPpLAKoQ3svivzmwY3x-h0',
                image_url: '09/game-main.jpg',
                isGameplay: true,
            },
            {
                name: 'DT',
                url: 'https://mega.nz/file/eB8jnCQC#DaVN0yZcqcy_Ec2durEmtSn50kecnm4KNSq7psekX1w',
                image_url: '09/game-dt.jpg',
                isGameplay: true,
            },
            {
                name: 'EZ',
                url: 'https://mega.nz/file/7V91BILB#Wc--4fpn8-z8QnyHYotDPr4OYA_JyJNM8EYJ4ZGXYiU',
                image_url: '09/game-ez.jpg',
                isGameplay: true,
            },
            {
                name: 'Hanoji',
                url: 'https://mega.nz/file/nRsVVKqA#I5YqAj2EdYm4lXyvM30RKhOFcSynOwJMG7cjdyrTB-s',
                image_url: '09/game-hnj.jpg',
                isGameplay: true,
            },
            {
                name: 'Alt',
                url: 'https://mega.nz/file/XI8xzaDA#V3RrWGscKV8hB9ihudpynGIOfmylRavyIyDPHBdp_jo',
                image_url: '09/game-alt.jpg',
                isGameplay: true,
            },
            {
                name: 'HR',
                url: 'https://mega.nz/file/KJthmIII#M05hzDc4qflpT3YaIrQ29-IPgBKbvKAG9mkXoULWVjc',
                image_url: '09/game-hr.jpg',
                isGameplay: true,
            },
            {
                name: 'EZ2',
                url: 'https://mega.nz/file/nE9REYQT#wzfpDxzQ7-oniIXgXdKbxbucuVEBFCryzO8AjTvHbhM',
                image_url: '09/game-ez2.jpg',
                isGameplay: true,
            },
            {
                name: 'Holo',
                url: 'https://mega.nz/file/OEsn2IzA#A5Oojj75YoVVuwi9U3LCurIcBxlmzJcosAASe5nbByE',
                image_url: '09/game-holo.jpg',
                isGameplay: true,
            },
            {
                name: 'No overlay',
                url: 'https://mega.nz/file/WctXgIhR#dc5S2YJvYLYaLsLc90gGKu9EzjzH6lLPVcKgrxylHas',
                image_url: '09/game-noover.jpg',
                isGameplay: true,
            },
            {
                name: 'Flashlight',
                url: 'https://mega.nz/file/KYsBHSYJ#xxl9HW3szxu2jOuQm6jgA3Sa9W73BSInC-FRDWG0jks',
                image_url: '09/game-fl.jpg',
                isGameplay: true,
            },
        ]
    },
    {
        id: '10',
        name: 'SBR UnDefined (UD)',
        date_start: '2021-10-12',
        date_end: '2022-03-12',
        url: 'https://www.mediafire.com/folder/dl3zeo0nt6oly/10th+skin+SBR+UnDefined',
        video_url: 'https://www.youtube.com/embed/xhc9azhyml8',
        images: [
            {
                name: 'Song select',
                url: 'url',
                image_url: '10/songselect.jpg',
                isGameplay: false,
            },
            {
                name: 'Mode select',
                url: 'url',
                image_url: '10/mode.jpg',
                isGameplay: false,
            },
            {
                name: 'Mod select',
                url: 'url',
                image_url: '10/mods.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking panel',
                url: 'url',
                image_url: '10/rank.jpg',
                isGameplay: false,
            },
            {
                name: '00 SaberStrike',
                url: 'https://www.mediafire.com/file/9fhl6cmtt890sf4/-_SBR_UD_00_SaberStrike.osk/file',
                image_url: '10/game-00.jpg',
                isGameplay: true,
            },
            {
                name: '01 FullCircle',
                url: 'https://www.mediafire.com/file/jwa8ye9up8jxyjf/-_SBR_UD_01FullCircle.osk/file',
                image_url: '10/game-01.jpg',
                isGameplay: true,
            },
            {
                name: '02 ThinMonochrome',
                url: 'https://www.mediafire.com/file/p3k7v0v8giydafb/-_SBR_UD_02ThinMonochrome.osk/file',
                image_url: '10/game-02.jpg',
                isGameplay: true,
            },
            {
                name: '03 Dot',
                url: 'https://www.mediafire.com/file/0ld40yfplju5zl2/-_SBR_UD_03Dot.osk/file',
                image_url: '10/game-03.jpg',
                isGameplay: true,
            },
            {
                name: '04 Crystallized',
                url: 'https://www.mediafire.com/file/jxu9115h2fpj9z2/-_SBR_UD_04Crystallized.osk/file',
                image_url: '10/game-04.jpg',
                isGameplay: true,
            },
            {
                name: '05 Stream',
                url: 'https://www.mediafire.com/file/zrhqkvwmtbf8vcg/-_SBR_UD_05Stream.osk/file',
                image_url: '10/game-05.jpg',
                isGameplay: true,
            },
            {
                name: '06 OldStyle',
                url: 'https://www.mediafire.com/file/h26spw6uij5t3dm/-_SBR_UD_06OldStyle.osk/file',
                image_url: '10/game-06.jpg',
                isGameplay: true,
            },
            {
                name: '07 GenericDT',
                url: 'https://www.mediafire.com/file/nunuvqh54etv6i1/-_SBR_UD_07GenericDT.osk/file',
                image_url: '10/game-07.jpg',
                isGameplay: true,
            },
            {
                name: '08 Bacon',
                url: 'https://www.mediafire.com/file/8uy9xkawn907xmw/-_SBR_UD_08Bacon.osk/file',
                image_url: '10/game-08.jpg',
                isGameplay: true,
            },
            {
                name: '09 Salmon',
                url: 'https://www.mediafire.com/file/kigo9h1wi1jcxhy/-_SBR_UD_09Salmon.osk/file',
                image_url: '10/game-09.jpg',
                isGameplay: true,
            },
            {
                name: '10 Cookie',
                url: 'https://www.mediafire.com/file/szsc8ums8w6vehk/-_SBR_UD_10Cookie.osk/file',
                image_url: '10/game-10.jpg',
                isGameplay: true,
            },
            {
                name: '11 Inverted',
                url: 'https://www.mediafire.com/file/y8t8tpld7220qvz/-_SBR_UD_11Inverted.osk/file',
                image_url: '10/game-11.jpg',
                isGameplay: true,
            },
            {
                name: '12 SpeedDemon',
                url: 'https://www.mediafire.com/file/dy5utepueccsjqa/-_SBR_UD_12SpeedDemon.osk/file',
                image_url: '10/game-12.jpg',
                isGameplay: true,
            },
            {
                name: '13 Colourful',
                url: 'https://www.mediafire.com/file/a8nkyj6qif16w8b/-_SBR_UD_13Colourful.osk/file',
                image_url: '10/game-13.jpg',
                isGameplay: true,
            },
            {
                name: '14 Glowy',
                url: 'https://www.mediafire.com/file/shp1x4xqinksldc/-_SBR_UD_14Glowy.osk/file',
                image_url: '10/game-14.jpg',
                isGameplay: true,
            },
            {
                name: '15 SalmonSelyu',
                url: 'https://www.mediafire.com/file/hl44q4r3wouv58d/-_SBR_UD_15SalmonSelyu.osk/file',
                image_url: '10/game-15.jpg',
                isGameplay: true,
            },
            {
                name: '16 HaNoJi',
                url: 'https://www.mediafire.com/file/nv6mluqcsd9jxam/-_SBR_UD_16_HaNoJi.osk/file',
                image_url: '10/game-16.jpg',
                isGameplay: true,
            },
            {
                name: '17 Seoulv10',
                url: 'https://www.mediafire.com/file/ufojpi08exclpvu/-_SBR_UD_17Seoulv10.osk/file',
                image_url: '10/game-17.jpg',
                isGameplay: true,
            },
            {
                name: '18 CherryKoro',
                url: 'https://www.mediafire.com/file/zc57qq54cyfj15a/-_SBR_UD_18Cherrykoro.osk/file',
                image_url: '10/game-18.jpg',
                isGameplay: true,
            },
            {
                name: 'ab DT',
                url: 'https://www.mediafire.com/file/m75rjdo4f3ujju7/-_SBR_UD_ab_DT.osk/file',
                image_url: '10/game-abdt.jpg',
                isGameplay: true,
            },
            {
                name: 'ac EZ',
                url: 'https://www.mediafire.com/file/wp00ccl6nzkp729/-_SBR_UD_ac_EZ.osk/file',
                image_url: '10/game-acez.jpg',
                isGameplay: true,
            },
            {
                name: 'taiko',
                url: './10#taiko.html',
                image_url: '10/game-taiko.jpg',
                isGameplay: true,
            },
            {
                name: 'ctb',
                url: './10#ctb.html',
                image_url: '10/game-ctb.jpg',
                isGameplay: true,
            },
            {
                name: 'mania',
                url: './10#mania.html',
                image_url: '10/game-mania.jpg',
                isGameplay: true,
            },
        ]
    },
    {
        id: '10.1',
        name: 'SBR UnDefined (UD) 10.1',
        date_start: '2021-10-12',
        date_end: '2022-03-12',
        url: 'https://www.mediafire.com/folder/8vob8x7pjw83v/v1.1',
        video_url: 'https://www.youtube.com/embed/xhc9azhyml8',
        images: [
            {
                name: '01 Fullcircle',
                url: 'https://www.mediafire.com/file/ici8ambe8opjwgu/-_SBR_UD_01FullCircle.osk/file',
                image_url: '10/1d1skin-01.jpg',
                isGameplay: true,
            },
            {
                name: '03 Dot',
                url: 'https://www.mediafire.com/file/lcku9w5dobkx2an/-_SBR_UD_03Dot.osk/file',
                image_url: '10/1d1skin-03.jpg',
                isGameplay: true,
            },
            {
                name: '07 GenericDT',
                url: 'https://www.mediafire.com/file/ye5ooe9pcuu2ih8/-_SBR_UD_07GenericDT.osk/file',
                image_url: '10/1d1skin-07.jpg',
                isGameplay: true,
            },
            {
                name: '19 Nebukoro',
                url: 'https://www.mediafire.com/file/rkso4i5b3q9wudz/-_SBR_UD_19Nebukoro.osk/file',
                image_url: '10/1d1skin-19.jpg',
                isGameplay: true,
            },
            {
                name: '20 FullBright',
                url: 'https://www.mediafire.com/file/jtl9ixraji20ff6/-_SBR_UD_20FullBright.osk/file',
                image_url: '10/1d1skin-20.jpg',
                isGameplay: true,
            },
            {
                name: 'v8 -s',
                url: 'https://www.mediafire.com/file/ls1n7o8my58dqct/-_SBR_UD_V8_-s.osk/file',
                image_url: '10/1d1skinv8s.jpg',
                isGameplay: true,
            },
        ]
    },
    {
        id: '11',
        name: 'SBR v11',
        date_start: '2022-03-10',
        date_end: '2023-01-08',
        url: 'https://www.mediafire.com/folder/qx8a47xx3ush3/11th_skin_sbr_v11',
        video_url: 'https://www.youtube.com/embed/bkU9O9iPKnQ',
        images: [
            {
                name: 'Main',
                url: 'https://www.mediafire.com/file/fxusw641phz20lb/-_SBR_v11.osk/file',
                image_url: '11/game-main-01.jpg',
                isGameplay: true,
            },
            {
                name: 'DT',
                url: 'https://www.mediafire.com/file/w43xyseoogx3lkt/-_SBR_v11_%25E3%2580%258EDT%25E3%2580%258F.osk/file',
                image_url: '11/game-main-dt.jpg',
                isGameplay: true,
            },
            {
                name: 'DT (old)',
                url: 'https://www.mediafire.com/file/gmb0j8zck1xkmx4/-_SBR_v11_%25E3%2580%258EDT_old%25E3%2580%258F.osk/file',
                image_url: '11/game-main-dtold.jpg',
                isGameplay: true,
            },
            {
                name: 'Dot',
                url: 'https://www.mediafire.com/file/q6um6my1du9ien1/-_SBR_v11_%25E3%2580%258EDot%25E3%2580%258F.osk/file',
                image_url: '11/game-main-dot.jpg',
                isGameplay: true,
            },
            {
                name: 'EZ',
                url: 'https://www.mediafire.com/file/4ixp1okai9ftofr/-_SBR_v11_%25E3%2580%258EEZ%25E3%2580%258F.osk/file',
                image_url: '11/game-main-ez.jpg',
                isGameplay: true,
            },
            {
                name: 'EZ2',
                url: 'https://www.mediafire.com/file/t6q83nuwewrkirn/-_SBR_v11_%25E3%2580%258EEZ2%25E3%2580%258F.osk/file',
                image_url: '11/game-main-ez2.jpg',
                isGameplay: true,
            },
            {
                name: 'Farming',
                url: 'https://www.mediafire.com/file/bsmd6t6vbxf8zs2/-_SBR_v11_%25E3%2580%258EFarming%25E3%2580%258F.osk/file',
                image_url: '11/game-main-farming.jpg',
                isGameplay: true,
            },
            {
                name: 'Full',
                url: 'https://www.mediafire.com/file/kgwnspfnm6a2p7z/-_SBR_v11_%25E3%2580%258EFullCircle%25E3%2580%258F.osk/file',
                image_url: '11/game-main-fullcircle.jpg',
                isGameplay: true,
            },
            {
                name: 'NM',
                url: 'https://www.mediafire.com/file/ngs73ayvwlzxjcc/-_SBR_v11_%25E3%2580%258ENM%25E3%2580%258F.osk/file',
                image_url: '11/game-main-nm.jpg',
                isGameplay: true,
            },
            {
                name: 'NM2',
                url: 'https://www.mediafire.com/file/3ujnuqedmtkod8a/-_SBR_v11_%25E3%2580%258ENM2%25E3%2580%258F.osk/file',
                image_url: '11/game-main-nm2.jpg',
                isGameplay: true,
            },
            {
                name: 'NM3',
                url: 'https://www.mediafire.com/file/93wvaqks02zcvjj/-_SBR_v11_%25E3%2580%258ENM3%25E3%2580%258F.osk/file',
                image_url: '11/game-main-nm3.jpg',
                isGameplay: true,
            },
            {
                name: 'UD',
                url: 'https://www.mediafire.com/file/ugzrrotm8efm29q/-_SBR_v11_%25E3%2580%258EUD_00%25E3%2580%258F.osk/file',
                image_url: '11/game-main-ud00.jpg',
                isGameplay: true,
            },
            {
                name: 'UD DT',
                url: 'https://www.mediafire.com/file/ke4jcchnb5s4vmn/-_SBR_v11_%25E3%2580%258EUD_DT%25E3%2580%258F.osk/file',
                image_url: '11/game-main-uddt.jpg',
                isGameplay: true,
            },
            {
                name: 'UD DT Dot',
                url: 'https://www.mediafire.com/file/qucrajx3e1z4rrn/-_SBR_v11_%25E3%2580%258EUD_DT_DOT%25E3%2580%258F.osk/file',
                image_url: '11/game-main-uddtdot.jpg',
                isGameplay: true,
            },
            {
                name: 'AR11',
                url: 'https://www.mediafire.com/file/6qkp6b4u6vi6zxp/-_SBR_v11_%25E3%2580%258EAR11%25E3%2580%258F.osk/file',
                image_url: '11/game-main-ar11.jpg',
                isGameplay: true,
            },
        ]
    },
    {
        id: '12',
        name: 'sbrstrkkdwmdr v12',
        date_start: '2023-01-08',
        date_end: '2023-06-01',
        url: 'https://www.mediafire.com/folder/2q7mtnk9a4dds/12th_skin_sbrstrkkdwmdr_v12',
        video_url: 'https://www.youtube.com/embed/jB03Z6x9VGU',
        images: [
            {
                name: 'Song select',
                url: 'url',
                image_url: '12/songselect.jpg',
                isGameplay: false,
            },
            {
                name: 'Mode select',
                url: 'url',
                image_url: '12/mode.jpg',
                isGameplay: false,
            },
            {
                name: 'Mods select',
                url: 'url',
                image_url: '12/mods.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking screen',
                url: 'url',
                image_url: '12/rank.jpg',
                isGameplay: false,
            },
            {
                name: 'Main',
                url: 'https://www.mediafire.com/file/zzbuiohnnludqum/-_sbrstrkkdw_v12.osk/file',
                image_url: '12/game-AA.jpg',
                isGameplay: true,
            },
            {
                name: 'Cookie',
                url: 'https://www.mediafire.com/file/3wnpq7agulubd1o/-_sbrstrkkdw_v12_Cookie.osk/file',
                image_url: '12/game-cookie.jpg',
                isGameplay: true,
            },
            {
                name: 'Dot',
                url: 'https://www.mediafire.com/file/cqm03ivk42a0zl3/-_sbrstrkkdw_v12_Dot.osk/file',
                image_url: '12/game-dot.jpg',
                isGameplay: true,
            },
            {
                name: 'DT',
                url: 'https://www.mediafire.com/file/0gwgsl20ar3ih48/-_sbrstrkkdw_v12_DT.osk/file',
                image_url: '12/game-dt.jpg',
                isGameplay: true,
            },
            {
                name: 'EZ',
                url: 'https://www.mediafire.com/file/gaq2w7duvpi32yv/-_sbrstrkkdw_v12_EZ.osk/file',
                image_url: '12/game-ez.jpg',
                isGameplay: true,
            },
            {
                name: 'Farming',
                url: 'https://www.mediafire.com/file/gbkbtrphgq6wx0y/-_sbrstrkkdw_v12_Farming.osk/file',
                image_url: '12/game-farming.jpg',
                isGameplay: true,
            },
            {
                name: 'Farm+dot',
                url: 'https://www.mediafire.com/file/8w9el75minqvhy2/-_sbrstrkkdw_v12_Farm%252Bdot.osk/file',
                image_url: '12/game-farm+dot.jpg',
                isGameplay: true,
            },
            {
                name: 'Flashlight',
                url: 'https://www.mediafire.com/file/nd2cngefhvyyyuc/-_sbrstrkkdw_v12_Flashlight.osk/file',
                image_url: '12/game-flashlight.jpg',
                isGameplay: true,
            },
            {
                name: 'Oldstyle',
                url: 'https://www.mediafire.com/file/ulbgvevhz3hgs5w/-_sbrstrkkdw_v12_OldStyle.osk/file',
                image_url: '12/game-oldstyle.jpg',
                isGameplay: true,
            },
            {
                name: 'Streaming',
                url: 'https://www.mediafire.com/file/9gn6wz5kq2477dp/-_sbrstrkkdw_v12_Streaming.osk/file',
                image_url: '12/game-streaming.jpg',
                isGameplay: true,
            },
        ]
    },
    {
        id: '12.1',
        name: 'sbrstrkkdwmdr v12.1',
        date_start: '2023-03-17',
        date_end: '2023-06-01',
        url: 'https://www.mediafire.com/folder/s3261nj0c2vzr/1.1',
        video_url: 'https://www.youtube.com/embed/5sayNtpLT0o',
        images: [
            {
                name: 'Song select',
                url: 'url',
                image_url: '12/12.1/songselect.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking screen',
                url: 'url',
                image_url: '12/12.1/rank_1.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking screen',
                url: 'url',
                image_url: '12/12.1/rank_2.jpg',
                isGameplay: false,
            },
            {
                name: 'Main',
                url: 'https://www.mediafire.com/file/d5vk5j41qv3mu44/-_sbrstrkkdw_v12.1_-.osk/file',
                image_url: '12/12.1/game-aamain.jpg',
                isGameplay: true,
            },
            {
                name: 'Altborder',
                url: 'https://www.mediafire.com/file/6cc4tyv0d544vh6/-_sbrstrkkdw_v12.1_AltBorder.osk/file',
                image_url: '12/12.1/game-alt.jpg',
                isGameplay: true,
            },
            {
                name: 'Cookie',
                url: 'https://www.mediafire.com/file/nay9a75qzpe91m9/-_sbrstrkkdw_v12.1_Cookie.osk/file',
                image_url: '12/12.1/game-cookie.jpg',
                isGameplay: true,
            },
            {
                name: 'Dot',
                url: 'https://www.mediafire.com/file/xc4cjlkhl7styye/-_sbrstrkkdw_v12.1_Dot.osk/file',
                image_url: '12/12.1/game-dot.jpg',
                isGameplay: true,
            },
            {
                name: 'DT',
                url: 'https://www.mediafire.com/file/gss68kq34tyit2o/-_sbrstrkkdw_v12.1_DT.osk/file',
                image_url: '12/12.1/game-dt.jpg',
                isGameplay: true,
            },
            {
                name: 'EZ',
                url: 'https://www.mediafire.com/file/h95ky5l71ic4i77/-_sbrstrkkdw_v12.1_EZ.osk/file',
                image_url: '12/12.1/game-ez.jpg',
                isGameplay: true,
            },
            {
                name: 'EZ2',
                url: 'https://www.mediafire.com/file/18oeav8je86vee1/-_sbrstrkkdw_v12.1_EZ2.osk/file',
                image_url: '12/12.1/game-ez2.jpg',
                isGameplay: true,
            },
            {
                name: 'Farm_alt',
                url: 'https://www.mediafire.com/file/wpo4bsokwitn5m5/-_sbrstrkkdw_v12.1_Farm_alt.osk/file',
                image_url: '12/12.1/game-farmalt.jpg',
                isGameplay: true,
            },
            {
                name: 'Farm+dot',
                url: 'https://www.mediafire.com/file/acz4pvj5on71gu6/-_sbrstrkkdw_v12.1_Farm%252Bdot.osk/file',
                image_url: '12/12.1/game-farm+dot.jpg',
                isGameplay: true,
            },
            {
                name: 'Farming',
                url: 'https://www.mediafire.com/file/uwud88tznelyqxh/-_sbrstrkkdw_v12.1_Farming.osk/file',
                image_url: '12/12.1/game-farming.jpg',
                isGameplay: true,
            },
            {
                name: 'Flashlight',
                url: 'https://www.mediafire.com/file/te17jpxy4ry16yp/-_sbrstrkkdw_v12.1_Flashlight.osk/file',
                image_url: '12/12.1/game-flashlight.jpg',
                isGameplay: true,
            },
            {
                name: 'Holo',
                url: 'https://www.mediafire.com/file/ruv76l3gu50cktg/-_sbrstrkkdw_v12.1_Holo.osk/file',
                image_url: '12/12.1/game-holo.jpg',
                isGameplay: true,
            },
            {
                name: 'HR',
                url: 'https://www.mediafire.com/file/en0j0fqpdp4zm5w/-_sbrstrkkdw_v12.1_HR.osk/file',
                image_url: '12/12.1/game-hr.jpg',
                isGameplay: true,
            },
            {
                name: 'Oldstyle',
                url: 'https://www.mediafire.com/file/fr2zz4bwobd8y58/-_sbrstrkkdw_v12.1_OldStyle.osk/file',
                image_url: '12/12.1/game-oldstyle.jpg',
                isGameplay: true,
            },
            {
                name: 'Streaming',
                url: 'https://www.mediafire.com/file/exdt4lafxcdicai/-_sbrstrkkdw_v12.1_Streaming.osk/file',
                image_url: '12/12.1/game-streaming.jpg',
                isGameplay: true,
            },
            {
                name: '404 (defreeyay) remake',
                url: 'https://www.mediafire.com/file/9if0czc0rtx1khe/-_sbrstrkkdw_v12_z_404skinnotfound_%2528defreeyay%2529.osk/file',
                image_url: '12/12.1/game-re404.jpg',
                isGameplay: true,
            },
        ]
    },
    {
        id: '13',
        name: 'sbrstrkkdw v13',
        date_start: '2023-06-01',
        date_end: '2024-03-03',
        url: 'https://www.mediafire.com/folder/2in6w671bx4i9',
        video_url: 'https://www.youtube.com/embed/_s3vIJBtaMo',
        images: [
            {
                name: '- h',
                url: 'https://www.mediafire.com/file/hxz6k56i9krwb2l/-_sbrstrkkdw_v13_-_h.osk/file',
                image_url: '13/g-h.jpg',
                isGameplay: true,
            },
            {
                name: 'DT',
                url: 'https://www.mediafire.com/file/i6g7xwndjxdprm6/-_sbrstrkkdw_v13_DT.osk/file',
                image_url: '13/g-dt.jpg',
                isGameplay: true,
            },
            {
                name: '- ho',
                url: 'https://www.mediafire.com/file/bk317sme29d9e56/-_sbrstrkkdw_v13_-_ho.osk/file',
                image_url: '13/g-ho.jpg',
                isGameplay: true,
            },
            {
                name: '- s',
                url: 'https://www.mediafire.com/file/nhgdget4xp73ylb/-_sbrstrkkdw_v13_-_s.osk/file',
                image_url: '13/g-s.jpg',
                isGameplay: true,
            },
            {
                name: 'FullCircle',
                url: 'https://www.mediafire.com/file/jiqnph6u261uui2/-_sbrstrkkdw_v13_FullCircle.osk/file',
                image_url: '13/g-fc.jpg',
                isGameplay: true,
            },
            {
                name: 'Song select',
                url: 'url',
                image_url: '13/img_ss.jpg',
                isGameplay: false,
            },
            {
                name: 'Mod select',
                url: 'url',
                image_url: '13/img_ms.jpg',
                isGameplay: false,
            },
            {
                name: 'Ranking panel',
                url: 'url',
                image_url: '13/img_rp.jpg',
                isGameplay: false,
            },
        ],
    },
    {
        id: '14',
        name: 'sbrstrkkdw v14',
        date_start: '2023-02-27',
        date_end: 'present',
        url: '14.html',
        video_url: 'https://www.youtube.com/embed/_s3vIJBtaMo',
        images: [
            {
                name: 'nothing yet',
                url: '14.html',
                image_url: 'WIP.png',
                isGameplay: true,
            },
        ]
    }

]