const conversionData = {
    temp_c: ['Celsius', '℃', '°C', 'Celcius', 'Centigrade', 'C',],
    temp_f: ['Fahrenheit', '℉', '°F', 'F'],
    temp_k: ['Kelvin', '°K', 'K'],
    dist_in: ['Inch', 'in', '\'', '`'],
    dist_ft: ['Feet', 'ft', 'foot', '"', "''", '``'],
    dist_m: ['Metre', 'm', 'Meter'],
    dist_mi: ['Mile', 'mi'],
    dist_au: ['Astronomical Unit', 'au'],
    dist_ly: ['Light Year', 'ly'],
    dist_pc: ['Parsec', 'pc'],
    time_s: ['Second', 's', 'sec'],
    time_min: ['Minute', 'min',],
    time_hr: ['Hour', 'h', 'hr'],
    time_d: ['Day', 'd',],
    time_wk: ['Week', 'wk', 'sennight',],
    time_fn: ['Fortnight', 'fn'],
    time_mth: ['Month', 'mth', 'mon'],
    time_qua: ['Quarantine', 'quarantina', 'quarentine'],
    time_yr: ['Year', 'yr',],
    time_dec: ['Decade', 'dec'],
    time_cen: ['Century', 'cent'],
    time_mil: ['Millennium', 'Millennia',],
    time_ma: ['Megaannum',],
    time_eon: ['Eon',],
    vol_tsp: ['Teaspoon', 'tsp',],
    vol_tbp: ['Tablespoon', 'tbp',],
    vol_floz: ['Fluid Ounce', 'floz'],
    vol_c: ['Cup', 'c',],
    vol_pt: ['Pint', 'pt',],
    vol_l: ['Litre', 'Liter', 'L'],
    vol_gal: ['Galloon', 'gal',],
    vol_m3: ['Cubic Metre', 'm³', 'm3', 'm^3'],
    mass_g: ['Gram', 'g'],
    mass_oz: ['Ounce', 'oz'],
    mass_lb: ['Pound', 'lb'],
    mass_st: ['Stone', 'st'],
    mass_t: ['US Ton', 't', 'Ton',],
    mass_mt: ['Metric Tonne', 'mt', 'Tonne',],
    pres_pa: ['Pascal', 'Pa', 'N m² ⁻¹', 'N/m^2', 'N/m', 'Nm'],
    pres_mmHg: ['millimetre of Mercury', 'mmHg', 'Torr', 'millimeter of Mercury',],
    pres_psi: ['Pounds per square inch', 'psi'],
    pres_bar: ['Bar'],
    pres_atm: ['Standard Atmosphere', 'atm', 'Atmosphere', 'std atm'],
    nrg_ev: ['Electron Volt', 'eV', 'Electronvolt'],
    nrg_j: ['Joule', 'j'],
    nrg_cal: ['Calorie', 'cal'],
    nrg_btu: ['British Thermal Unit', 'btu'],
    nrg_wh: ['Watt Hour', 'wH'],
    pow_w: ['Watt', 'w'],
    pow_horse: ['Horse Power', 'hp'],
    pow_erg: ['Ergs', 'erg s⁻¹', 'erg/s'],
    pow_ftlbsec: ['Foot-pounds per second', 'ft lb s⁻¹', 'ftlb/s', 'ft lb s', 'ftlbs', 'ftlbsec', 'ft lb sec'],
    pow_dbm: ['Decibel-milliwatts', 'dBm', 'dbmw'],
    pow_btusec: ['BTU per second', 'btu s⁻¹', 'btus', 'btusec',],
    pow_calsec: ['Calories per second', 'cal s⁻¹', 'cals', 'calsec'],
    area_in2: ['Square inch', 'in²', 'in2', 'sqin'],
    area_ft2: ['Square foot', 'ft²', 'ft2', 'sqft'],
    area_m2: ['Square metre', 'm²', 'm2', 'sqm'],
    area_ac: ['Acre', 'ac'],
    area_ha: ['Hectare', 'Ha'],
    area_km2: ['Square kilometre', 'km²', 'km2', 'sqkm'],
    area_mi2: ['Square mile', 'mi²', 'mi2', 'sqmi'],
    angle_grad: ['Gradian', 'grad'],
    angle_deg: ['Degree', 'deg'],
    angle_rad: ['Radian', 'rad'],
    speed_kmh: ['Kilometres per hour', 'km h⁻¹', 'kmh', 'kph', 'km/h'],
    speed_mph: ['Miles per hour', 'mi h⁻¹', 'mph', 'mih', 'mi/h', 'm/h'],
    speed_kt: ['Knot', 'kt', 'nmi h⁻¹', 'nmih', 'nmh', 'Nautical miles per hour'],
    speed_ms: ['Metres per second', 'm s⁻¹', 'ms', 'mps', 'm/s',],
    speed_c: ['Light', 'c', 'lightspeed'],
    // base_bin: ['Binary', 'bin', 'base2'],
    // base_oct: ['Octal', 'oct', 'base8'],
    // base_dec: ['Decimal', 'dec', 'base10'],
    // base_hex: ['Hexadecimal', 'hex', 'base16'],
}


function convert() {
    const dat = [];
    for (const key in conversionData) {
        let cat = key.split('_')[0];
        let display = conversionData[key].join(' / ');
        dat.push({ id: key, cat, display })
    }
    for (const elem of dat) {
        const tempData = document.getElementById("conv_" + elem.cat);
        tempData.innerText += elem.display + '\n ';
    }
}